
version: '3.0'
services:
  web:
    build: .
    depends_on:
      - redis
    ports:
      - 5000:5000
    volumes:
      - .:/code
    environment:
      FLASK_ENV: development
      REDIS_HOST: redis
      REDIS_PORT: 6379
  redis:
    image: redis:6.0-rc3
    volumes:
      - redis_data:/data

volumes:
  redis_data:
